-- Log when we send a "flagged order" notification to staff (one per order per day)
-- Used to avoid sending duplicate emails for the same stuck order on the same day

CREATE TABLE IF NOT EXISTS public.flagged_order_notification_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  order_id text NOT NULL,
  notified_date date NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT flagged_order_notification_log_pkey PRIMARY KEY (id),
  CONSTRAINT flagged_order_notification_log_order_date_key UNIQUE (order_id, notified_date)
);

CREATE INDEX IF NOT EXISTS flagged_order_notification_log_notified_date_idx
  ON public.flagged_order_notification_log(notified_date);

ALTER TABLE public.flagged_order_notification_log ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Service role only" ON public.flagged_order_notification_log
  FOR ALL
  USING (false)
  WITH CHECK (false);

COMMENT ON TABLE public.flagged_order_notification_log IS 'Tracks flagged (stuck) order notifications sent to staff; one row per order per day to enforce at most one email per order per day';
