-- Create api_tokens table for storing OAuth refresh tokens
-- This table stores refresh tokens that need to be rotated/updated periodically

CREATE TABLE IF NOT EXISTS public.api_tokens (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  token_key text NOT NULL,
  token_value text NOT NULL,
  expires_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT api_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT api_tokens_token_key_key UNIQUE (token_key)
);

-- Create index on token_key for faster lookups
CREATE INDEX IF NOT EXISTS api_tokens_token_key_idx 
  ON public.api_tokens(token_key);

-- Create index on expires_at for monitoring token expiration
CREATE INDEX IF NOT EXISTS api_tokens_expires_at_idx 
  ON public.api_tokens(expires_at);

-- Enable RLS (Row Level Security)
ALTER TABLE public.api_tokens ENABLE ROW LEVEL SECURITY;

-- Create policy: Only service role can access (this table is accessed via service_role key)
CREATE POLICY "Service role only" ON public.api_tokens
  FOR ALL
  USING (false) -- Deny all access by default
  WITH CHECK (false);

-- Note: Since this table is accessed via service_role key (getSupabaseAdmin()),
-- the RLS policies don't apply. The policy above is just for safety.
-- The service_role key bypasses RLS.

-- Create function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_api_tokens_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger to automatically update updated_at
CREATE TRIGGER update_api_tokens_updated_at
  BEFORE UPDATE ON public.api_tokens
  FOR EACH ROW
  EXECUTE FUNCTION update_api_tokens_updated_at();

-- Add comments
COMMENT ON TABLE public.api_tokens IS 'Stores OAuth refresh tokens and API tokens that need periodic rotation';
COMMENT ON COLUMN public.api_tokens.token_key IS 'Unique identifier for the token (e.g., barron_refresh_token)';
COMMENT ON COLUMN public.api_tokens.token_value IS 'The actual token value (encrypted in production recommended)';
COMMENT ON COLUMN public.api_tokens.expires_at IS 'When the token expires (if known)';

