-- Create whatsapp_human_control table for tracking human control state
-- This table stores whether a human agent is in control for each WhatsApp session

CREATE TABLE IF NOT EXISTS public.whatsapp_human_control (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  session_id text NOT NULL,
  is_human_controlled boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT whatsapp_human_control_pkey PRIMARY KEY (id),
  CONSTRAINT whatsapp_human_control_session_id_key UNIQUE (session_id)
);

-- Create index on session_id for faster lookups
CREATE INDEX IF NOT EXISTS whatsapp_human_control_session_id_idx 
  ON public.whatsapp_human_control(session_id);

-- Create index on is_human_controlled for queries
CREATE INDEX IF NOT EXISTS whatsapp_human_control_is_human_controlled_idx 
  ON public.whatsapp_human_control(is_human_controlled);

-- Enable RLS (Row Level Security)
ALTER TABLE public.whatsapp_human_control ENABLE ROW LEVEL SECURITY;

-- Create policy: Only service role can access (this table is accessed via service_role key)
CREATE POLICY "Service role only" ON public.whatsapp_human_control
  FOR ALL
  USING (false) -- Deny all access by default
  WITH CHECK (false);

-- Note: Since this table is accessed via service_role key (getSupabaseAdmin()),
-- the RLS policies don't apply. The policy above is just for safety.
-- The service_role key bypasses RLS.

-- Create function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_whatsapp_human_control_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger to automatically update updated_at
CREATE TRIGGER update_whatsapp_human_control_updated_at
  BEFORE UPDATE ON public.whatsapp_human_control
  FOR EACH ROW
  EXECUTE FUNCTION update_whatsapp_human_control_updated_at();

-- Add comments
COMMENT ON TABLE public.whatsapp_human_control IS 'Stores human control state for WhatsApp sessions. When true, AI will not respond to incoming messages.';
COMMENT ON COLUMN public.whatsapp_human_control.session_id IS 'WhatsApp session ID (e.g., ML-27123456789)';
COMMENT ON COLUMN public.whatsapp_human_control.is_human_controlled IS 'Whether a human agent is currently in control of this session';

