-- Create email_processing_log table for tracking processed emails
-- This table logs emails that have been processed by the email AI agent

CREATE TABLE IF NOT EXISTS public.email_processing_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  message_id text NOT NULL,
  thread_id text,
  sender_email text NOT NULL,
  subject text,
  category text,
  processed_at timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT email_processing_log_pkey PRIMARY KEY (id),
  CONSTRAINT email_processing_log_message_id_key UNIQUE (message_id)
);

-- Create index on sender_email for faster lookups
CREATE INDEX IF NOT EXISTS email_processing_log_sender_email_idx ON public.email_processing_log(sender_email);

-- Create index on processed_at for time-based queries
CREATE INDEX IF NOT EXISTS email_processing_log_processed_at_idx ON public.email_processing_log(processed_at);

-- Enable RLS (Row Level Security)
ALTER TABLE public.email_processing_log ENABLE ROW LEVEL SECURITY;

-- Create policy: Only service role can access (this is a logging table, not for public access)
-- In practice, this table is only accessed via service_role key, so we can restrict all access
CREATE POLICY "Service role only" ON public.email_processing_log
  FOR ALL
  USING (false) -- Deny all access by default
  WITH CHECK (false);

-- Note: Since this table is accessed via service_role key (getSupabaseAdmin()),
-- the RLS policies don't apply. The policy above is just for safety.
-- The service_role key bypasses RLS.

COMMENT ON TABLE public.email_processing_log IS 'Logs emails processed by the MerchLab email AI agent';
COMMENT ON COLUMN public.email_processing_log.message_id IS 'Gmail message ID (unique identifier)';
COMMENT ON COLUMN public.email_processing_log.thread_id IS 'Gmail thread ID for email threading';
COMMENT ON COLUMN public.email_processing_log.sender_email IS 'Email address of the sender';
COMMENT ON COLUMN public.email_processing_log.subject IS 'Email subject line';
COMMENT ON COLUMN public.email_processing_log.category IS 'Categorized email type (e.g., order_status, quote_request, etc.)';
COMMENT ON COLUMN public.email_processing_log.processed_at IS 'Timestamp when the email was processed';

